# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a633390cd37d0c00edf86ec6f281cde191ccc9a46a10b822007a78e3c8a1dca57cd695dc2fb30d911d3cb528a14525a30ae9c6f6988f54d0c5b9edb33152521

test:
  secret_key_base: 15f72fd1b8e716e6569fc6346cbe619ab6f24c6d58143a21fd7b7e5f300fa107c7d728a7b1cd190b5f1d1bd6ba56ce973f7f7307edaa1b237743033b3f5a2d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4a633390cd37d0c00edf86ec6f281cde191ccc9a46a10b822007a78e3c8a1dca57cd695dc2fb30d911d3cb528a14525a30ae9c6f6988f54d0c5b9edb33152521
